learn/app/courses/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *


app_name = 'courses'

urlpatterns = [
    path('classes/', login_required(ClassesView.as_view()), name='classes'),
    path("classes/<int:pk>/", login_required(ClassesUpdateView.as_view()),
         name="class-update"),
    path("classes/<int:pk>/delete/",
         login_required(ClassesDeleteView.as_view()), name="class-delete"),
    path('subjects/',  login_required(SubjectsView.as_view()), name='subjects'),
    path("subject/<int:pk>/", login_required(SubjectUpdateView.as_view()),
         name="subject-update"),
    path("subject/<int:pk>/delete/",
         login_required(SubjectDeleteView.as_view()), name="subject-delete"),
    path('chapters/',  login_required(ChapterView.as_view()), name='chapters'),
    path("chapter/<int:pk>/", login_required(ChapterUpdateView.as_view()),
         name="chapter-update"),
    path("chapter/<int:pk>/delete/",
         login_required(ChapterDeleteView.as_view()), name="chapter-delete"),
    path('lessons/',  login_required(LessonView.as_view()), name='lessons'),
    path("lesson/<int:pk>/", login_required(LessonUpdateView.as_view()),
         name="lesson-update"),
    path("lesson/<int:pk>/status/",
         login_required(lesson_status_update), name="lesson-status-update"),
    path("lesson/<int:pk>/detail/",
         login_required(LessonDetailView.as_view()), name="lesson-detail"),
    path("lesson/<int:pk>/delete/",
         login_required(LessonDeleteView.as_view()), name="lesson-delete"),
    path('categories/', login_required(CategoriesView.as_view()), name='categories'),
    path("categories/<int:pk>/",
         login_required(CategoriesUpdateView.as_view()), name="category-update"),
    path("categories/<int:pk>/delete/",
         login_required(CategoriesDeleteView.as_view()), name="category-delete"),
    path('quizzes/', login_required(QuizView.as_view()), name='quizzes'),
    path('quizzes/create', login_required(QuizCreateView.as_view()), name='quizzes-create'),
    path("quizzes/<int:pk>/",
         login_required(QuizUpdateView.as_view()), name="quiz-update"),
    path("quizzes/<int:pk>/delete/",
         login_required(QuizDeleteView.as_view()), name="quiz-delete"),
    path("assignments/", login_required(AssignmentListView.as_view()), name="assignments"),
    path("assignment/<int:pk>", login_required(AssignmentUpdateView.as_view()), name="assignment-update"),
    path("assignment/<int:pk>/delete", login_required(AssignmentDeleteView.as_view()), name="assignment-delete"),
    path("assignment/<int:pk>/detail", login_required(AssignmentDetailView.as_view()), name="assignment-detail"),
    path("assignment/<int:pk>/submissions", login_required(AssignmentSubmissionsView.as_view()), name="assignment-submissions"),
    path("assignment/submission/<int:pk>/review", login_required(AssignmentReviewView.as_view()), name="submission-review"),
    path("assignment/submit",login_required(AssignmentSubmitView.as_view()),name='assignment-submit'),
]

learn/core/urls.py
from django.contrib import admin
from django.urls import include, path
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt
from .settings import DEBUG

urlpatterns = [
    path("", include("app.accounts.urls", namespace="core")),
    path("chart/", include("app.charts.urls")),
    path("courses/", include("app.courses.urls")),
    path('admin/', admin.site.urls),
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True)), name="graphql"),
]

if DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

learn/app/courses/models.py
from django.db import models
from app.accounts.models import User
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator
from ..accounts.models import Enrollment


class Classes(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(
        upload_to='uploads/classes', blank=True, null=True)
    slug = models.SlugField(unique=True, max_length=255)
    latest_price = models.FloatField(
        default=0.0, validators=[MinValueValidator(0.0)])
    before_price = models.FloatField(
        default=0.0, validators=[MinValueValidator(0.0)])
    postition = models.IntegerField(blank=True, null=True)
    publish_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'classes'


class Category(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.TextField(max_length=255, blank=True, null=True)
    popular = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'categories'


class Subject(models.Model):
    name = models.CharField(max_length=255)
    short = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, max_length=255)
    image = models.ImageField(
        upload_to='uploads/subjects', blank=True, null=True)
    publish_at = models.DateTimeField(blank=True, null=True)
    standard = models.ForeignKey(Classes, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name + ' - ' + self.standard.name

    class Meta:
        db_table = 'subjects'


class Chapter(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(
        upload_to='uploads/chapters', blank=True, null=True)
    collectionid = models.CharField(
        db_column='collectionId', max_length=255, blank=True, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name + ' - ' + self.subject.name + ' - ' + self.subject.standard.name

    class Meta:
        db_table = 'chapters'


class Quiz(models.Model):
    class Type(models.TextChoices):
        Mock = 'mock', _('Mock')
        Practice = 'practice', _('Practice')

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=Type.choices)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    publish_at = models.DateTimeField(auto_now_add=True)
    time_required = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'quizzes'


class Question(models.Model):
    question_text = models.TextField()
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    figure = models.ImageField(
        upload_to='uploads/', blank=True, null=True, verbose_name=_("Figure"))

    def __str__(self):
        return self.question_text

    class Meta:
        db_table = 'questions'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.choice_text

    class Meta:
        db_table = 'choices'


class Assignment(models.Model):
    class Type(models.TextChoices):
        Mock = 'mock', _('Mock')
        Practice = 'practice', _('Practice')
    title = models.CharField(max_length=200)
    description = models.TextField()
    due_date = models.DateTimeField(blank=True, null=True)
    teacher = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True)
    assigment_file = models.FileField(upload_to='uploads/assignments', blank=True, null=True)
    type = models.CharField(max_length=20, choices=Type.choices)
    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name='assignment_created_by', blank=True, null=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='assignment_updated_by')
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class AssignmentSubmission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    solution_file = models.FileField(
        upload_to='uploads/assignments/submissions')
    reviewed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    marks = models.IntegerField(blank=True,
                                null=True,
                                validators=[MinValueValidator(0)]
    )
    remarks = models.TextField(blank=True,null=True)
    def __str__(self):
        return f"{self.assignment.title} - {self.student.full_name}"


class Grades(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    enrolled_class = models.ForeignKey(Classes, on_delete=models.CASCADE)
    assignment = models.ForeignKey(
        Assignment, null=True, blank=True, on_delete=models.CASCADE)
    quiz = models.ForeignKey(
        Quiz, null=True, blank=True, on_delete=models.CASCADE)
    grade = models.DecimalField(max_digits=2,
                                decimal_places=1,
                                validators=[MinValueValidator(0.0), MaxValueValidator(10.0)])
    # enrollment = models.ForeignKey(Enrollment,blank=False,null=False,on_delete=models.CASCADE)

    def __str__(self):
        if self.assignment:
            return f"{self.student.full_name} - Class {self.enrolled_class} - Assignment: {self.assignment.title} - Score: {self.grade}"
        elif self.quiz:
            return f"{self.student.full_name} - Class {self.enrolled_class} - Quiz: {self.quiz.name} - Score: {self.grade}"
        return f"{self.student.full_name} - Class {self.enrolled_class} - Score: {self.grade}"


class Lesson(models.Model):
    class UploadStatus(models.TextChoices):
        CREATED = 'created', _('Created')
        PENDING = 'pending', _('Pending')
        UPLOADING = 'uploading', _('Uploading')
        PROCESSING = 'processing', _('Processing')
        READY = 'ready', _('Ready')
        ERROR = 'error', _('Error')

    class LessonType(models.TextChoices):
        NONE = None, _('---------')
        VIDEO = 'video', _('Video')
        DOCUMENT = 'document', _('Document')
        IMAGE = 'image', _('Image')
        TEXT = 'text', _('Text')
        QUIZ = 'quiz', _('Quiz')

    class SupportPlatform(models.TextChoices):
        FILE = 'file', _('File')
        YOUTUBE = 'youtube', _('Youtube')
        VIMEO = 'vimeo', _('Vimeo')

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    length = models.FloatField(blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    thumb_url = models.ImageField(
        upload_to='uploads/lessons', blank=True, null=True)
    public = models.BooleanField(default=False)
    position = models.IntegerField(blank=True, null=True, default=9999)
    lesson_type = models.CharField(
        db_column='type', max_length=8, choices=LessonType.choices, default=None)
    status = models.CharField(
        max_length=10, choices=UploadStatus.choices, default=UploadStatus.CREATED)
    platform = models.CharField(
        max_length=11, blank=True, null=True, choices=SupportPlatform.choices, default=None)
    platform_video_id = models.CharField(max_length=255, blank=True, null=True)
    teacher = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='teacher')
    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name='created_by', blank=True, null=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='updated_by')
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    quiz = models.ForeignKey(
        Quiz, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:

learn/app/courses/views/categories.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
# from django.utils.text import slugify
from django.urls import reverse_lazy
from ..models import Category
from ..forms import CategoriesForm


class CategoriesView(ListView):
    model = Category
    template_name = "categories/index.html"
    form = CategoriesForm
    context_object_name = "categories"
    extra_context = {
        'title': 'Categories',
        'breadcrumbs': [{'url': 'core:home', 'label': 'Dashboard'}, {'label': 'Courses'}, {'label': 'Categories'}],
        'form': form
    }
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for obj in context[self.context_object_name]:
            temp_form = CategoriesForm(instance=obj)
            obj.form = temp_form
        return context

    # create
    def post(self, request, **kwargs):
        form = self.form(request.POST)
        self.extra_context.update({'form': form})
        if form.is_valid():
            instance = form.save(commit=False)
            # instance.slug = slugify(instance.name)
            instance.save()
            messages.success(
                request, f'{instance.name} has been created successfully.')
            self.extra_context.update({'form': CategoriesForm})
            return redirect('courses:categories')
        else:
            messages.error(request, f'failed to create! please see the create form for more details.')
            return super().get(request, **kwargs)

    #filter
    def get_queryset(self):
        queryset = super().get_queryset()
        subject_name = self.request.GET.get('subject')

        if subject_name:
            queryset = queryset.filter(name__icontains=subject_name)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subject_filter'] = self.request.GET.get('subject', '')
        return context


class CategoriesUpdateView(UpdateView):
    model = Category
    form_class = CategoriesForm
    success_url = reverse_lazy("courses:categories")
    template_name = "form.html"

    def form_valid(self, form):
        # form.instance.slug = slugify(form.instance.name)
        messages.info(
            self.request, f'{form.instance.name} has been updated successfully.')
        return super().form_valid(form)


class CategoriesDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy("courses:categories")

    def get(self, request, **kwargs):
        messages.error(request, 'Category has been deleted successfully.')
        return self.delete(request, **kwargs)

learn/app/courses/templates/chapters/index.html
{% extends "layouts/dashboard.html" %}
{% load static %}
{% block title %}
  {{ title }} | Pramey Shala
{% endblock title %}
{% block content %}
  <div class="mt-12 mb-8 flex flex-col gap-12">
    <div class="flex justify-between px-6">
      {% if perms.courses.add_chapter %}
        <button onclick="create_chapter.showModal()"
                class="btn bg-gradient-to-br from-purple-600 to-pink-400 text-white px-12 border-0 shadow-md shadow-purple-500/50">
          <i class="far fa-plus"></i>Add Chapter
        </button>
      {% endif %}
      <form id="filter-form" method="get" action="{% url 'courses:chapters' %}">
        <select class="select select-bordered max-w-xs"
                name="subject"
                id="subject-select"
                placeholder="All Subjects">
          <option class="text-left"
                  value=""
                  {% if not subject_filter %}selected{% endif %}>All Subjects</option>
          <option class="text-left"
                  value="Physics"
                  {% if subject_filter == 'Physics' %}selected{% endif %}>Physics</option>
          <option class="text-left"
                  value="Chemistry"
                  {% if subject_filter == 'Chemistry' %}selected{% endif %}>Chemistry</option>
          <option class="text-left"
                  value="Math"
                  {% if subject_filter == 'Math' %}selected{% endif %}>Maths</option>
          <option class="text-left"
                  value="Biology"
                  {% if subject_filter == 'Biology' %}selected{% endif %}>Biology</option>
        </select>
        <select class="select select-bordered max-w-xs"
                name="class"
                id="class-select"
                placeholder="All Classes">
          <option class="text-left"
                  value=""
                  {% if not subject_filter %}selected{% endif %}>All Classes</option>
          <option class="text-left"
                  value="Class 9th"
                  {% if subject_filter == 'Class 9th' %}selected{% endif %}>Class 9th</option>
          <option class="text-left"
                  value="Class 10th"
                  {% if subject_filter == 'Class 10th' %}selected{% endif %}>Class 10th</option>
          <option class="text-left"
                  value="Class 11th"
                  {% if subject_filter == 'Class 11th' %}selected{% endif %}>Class 11th</option>
          <option class="text-left"
                  value="Class 12th"
                  {% if subject_filter == 'Class 12th' %}selected{% endif %}>Class 12th</option>
        </select>
        <select class="select select-bordered max-w-xs"
                name="chapter"
                id="chapter-select"
                placeholder="All Chapter">
          <option class="text-left"
                  value=""
                  {% if not subject_filter %}selected{% endif %}>All Chapters</option>
          <option class="text-left"
                  value="Chapter 1"
                  {% if subject_filter == 'Chapter 1' %}selected{% endif %}>Chapter 1</option>
          <option class="text-left"
                  value="Chapter 2"
                  {% if subject_filter == 'Chapter 2' %}selected{% endif %}>Chapter 2</option>
          <option class="text-left"
                  value="Chapter 3"
                  {% if subject_filter == 'Chapter 3' %}selected{% endif %}>Chapter 3</option>
          <option class="text-left"
                  value="Chapter 4"
                  {% if subject_filter == 'Chapter 4' %}selected{% endif %}>Chapter 4</option>
          <option class="text-left"
                  value="Chapter 5"
                  {% if subject_filter == 'Chapter 5' %}selected{% endif %}>Chapter 5</option>
          <option class="text-left"
                  value="Chapter 6"
                  {% if subject_filter == 'Chapter 6' %}selected{% endif %}>Chapter 6</option>
          <option class="text-left"
                  value="Chapter 7"
                  {% if subject_filter == 'Chapter 7' %}selected{% endif %}>Chapter 7</option>
          <option class="text-left"
                  value="Chapter 8"
                  {% if subject_filter == 'Chapter 8' %}selected{% endif %}>Chapter 8</option>
          <option class="text-left"
                  value="Chapter 9"
                  {% if subject_filter == 'Chapter 9' %}selected{% endif %}>Chapter 9</option>
          <option class="text-left"
                  value="Chapter 10"
                  {% if subject_filter == 'Chapter 10' %}selected{% endif %}>Chapter 10</option>
        </select>
        <button class="btn bg-gradient-to-br from-indigo-600 to-purple-400 text-white px-3 border-0 shadow-md shadow-purple-500/50"
                type="button"
                id="clear-filter">Clear Filter</button>
      </form>
    </div>
    <div class="relative flex w-full flex-col rounded-xl bg-base-100 bg-clip-border text-base-content shadow-md">
      <div class="relative mx-4 -mt-6 mb-4 grid px-6 py-8 overflow-hidden rounded-xl bg-gradient-to-tr from-indigo-600 to-indigo-400 bg-clip-border text-white shadow-lg shadow-indigo-500/40">
        <h1 class="block font-sans leading-snug tracking-normal text-white antialiased text-lg font-semibold">{{ title }}</h1>
      </div>
      <div class="flex flex-col gap-4 p-6 overflow-x-auto">
        <table class="table table-auto">
          <thead class="text-sm uppercase">
            <tr>
              <th class="px-4 py-3">Name</th>
              <th class="px-4 py-3">Description</th>
              <th class="px-4 py-3">Course</th>
              <th class="px-4 py-3">Collection ID</th>
              <th class="px-4 py-3">Action</th>
            </tr>
          </thead>
          <tfoot class="text-sm uppercase">
            <tr>
              <th class="px-4 py-3">Name</th>
              <th class="px-4 py-3">Description</th>
              <th class="px-4 py-3">Course</th>
              <th class="px-4 py-3">Collection ID</th>
              <th class="px-4 py-3">Action</th>
            </tr>
          </tfoot>
          <tbody>
            {% for chapter in chapters %}
              <tr class="border-b border-blue-gray-50">
                <td class="px-4 py-3">{{ chapter.name }}</td>
                <td class="px-4 py-3">{{ chapter.description }}</td>
                <td class="px-4 py-3">{{ chapter.subject }}</td>
                <td class="px-4 py-3">{{ chapter.collectionid }}</td>
                <td class="flex gap-2 px-4 py-3">
                  {% if perms.courses.change_chapter %}
                    <button onclick="update_chapter_{{ chapter.pk }}.showModal()"
                            class="btn btn-sm btn-success btn-square">
                      <i class="fad fa-edit"></i>
                    </button>
                  {% endif %}
                  {% if perms.courses.delete_chapter %}
                    <a href="{% url 'courses:chapter-delete' pk=chapter.pk %}"
                       onclick="if(confirm('Are you sure you want to delete {{ chapter.name }} from database?')) return true; else return false;"
                       class="btn btn-sm btn-error btn-square">
                      <i class="far fa-trash-alt"></i>
                    </a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="p-5 flex justify-end">
    <div class="join">
      {% if page_obj.has_previous %}
        <a class="join-item btn btn-primary"
           href="?page={{ page_obj.previous_page_number }}{% if subject_filter %}&subject={{ subject_filter }}{% endif %}{% if class_filter %}&class={{ class_filter }}{% endif %}{% if chapter_filter %}&chapter={{ chapter_filter }}{% endif %}">
          Previous
        </a>
      {% endif %}
      <span class="join-item btn btn-disabled">Page {{ page_obj.number }} of {{ paginator.num_pages }}.</span>
      {% if page_obj.has_next %}
        <a class="join-item btn btn-primary"
           href="?page={{ page_obj.next_page_number }}{% if subject_filter %}&subject={{ subject_filter }}{% endif %}{% if class_filter %}&class={{ class_filter }}{% endif %}{% if chapter_filter %}&chapter={{ chapter_filter }}{% endif %}">
          Next
        </a>
      {% endif %}
    </div>
  </div>
  {% if perms.courses.add_chapter %}
    <dialog id="create_chapter"
            class="modal modal-bottom sm:modal-middle transition-all duration-500 ease-in-out">
      <form method="post"
            enctype="multipart/form-data"
            class="modal-box sm:max-w-5xl">
        {% csrf_token %}
        <h2 class="font-mono font-semibold text-lg">Add New Chapter</h2>
        <div class="relative mb-4">
          <div class="form-control w-full djanog-custom-forms grid grid-cols-1 md:grid-cols-2 gap-4">{{ form.as_div }}</div>
        </div>
        <div class="modal-action justify-between">
          <p class="text-xs mt-auto">Press esc to close the window or outside the dialog box.</p>
          <button type="submit" class="btn btn-success">Add</button>
        </div>
      </form>
      <form method="dialog" class="modal-backdrop backdrop-blur-md">
        <button>close</button>
      </form>
    </dialog>
  {% endif %}
  {% if perms.courses.change_chapter %}
    {% for chapter in chapters %}
      <dialog id="update_chapter_{{ chapter.pk }}"
              class="modal modal-bottom sm:modal-middle transition-all duration-500 ease-in-out">
        <form method="post"
              enctype="multipart/form-data"
              action="{% url 'courses:chapter-update' pk=chapter.pk %}"
              class="modal-box sm:max-w-5xl">
          {% csrf_token %}
          <h2 class="font-mono font-semibold text-lg">Update - {{ chapter.name }} in {{ chapter.subject.name }}</h2>
          <div class="relative mb-4">
            <div class="form-control w-full djanog-custom-forms grid grid-cols-1 md:grid-cols-2 gap-4">
              {{ chapter.form.as_div }}
            </div>
          </div>
          <div class="modal-action justify-between">
            <p class="text-xs mt-auto">Press esc to close the window or outside the dialog box.</p>
            <button type="submit" class="btn btn-success shadow">Update</button>
          </div>
        </form>
        <form method="dialog" class="modal-backdrop backdrop-blur-md">
          <button>close</button>
        </form>
      </dialog>
      <script>
    document.addEventListener('DOMContentLoaded', function () {
        const filterForm = document.getElementById('filter-form');
        const subjectSelect = document.getElementById('subject-select');
        const classSelect = document.getElementById('class-select');
        const chapterSelect = document.getElementById('chapter-select');
        const clearFilterButton = document.getElementById('clear-filter');
        
        const urlParams = new URLSearchParams(window.location.search);
        const subjectFilter = urlParams.get('subject');
        const classFilter = urlParams.get('class');
        const chapterFilter = urlParams.get('chapter');
        
        subjectSelect.value = subjectFilter || "";
        classSelect.value = classFilter || "";
        chapterSelect.value = chapterFilter || "";
        
        filterForm.addEventListener('change', function (event) {
            if (event.target.tagName === 'SELECT') {
                filterForm.submit();
            }
        });

        clearFilterButton.addEventListener('click', function () {
            subjectSelect.value = '';
            classSelect.value = '';
            chapterSelect.value = '';
            filterForm.submit();
        });
    });
      </script>
    {% endfor %}
  {% endif %}
{% endblock content %}