learn/app/courses/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *


app_name = 'courses'

urlpatterns = [
    path('classes/', login_required(ClassesView.as_view()), name='classes'),
    path("classes/<int:pk>/", login_required(ClassesUpdateView.as_view()),
         name="class-update"),
    path("classes/<int:pk>/delete/",
         login_required(ClassesDeleteView.as_view()), name="class-delete"),
    path('subjects/',  login_required(SubjectsView.as_view()), name='subjects'),
    path("subject/<int:pk>/", login_required(SubjectUpdateView.as_view()),
         name="subject-update"),
    path("subject/<int:pk>/delete/",
         login_required(SubjectDeleteView.as_view()), name="subject-delete"),
    path('chapters/',  login_required(ChapterView.as_view()), name='chapters'),
    path("chapter/<int:pk>/", login_required(ChapterUpdateView.as_view()),
         name="chapter-update"),
    path("chapter/<int:pk>/delete/",
         login_required(ChapterDeleteView.as_view()), name="chapter-delete"),
    path('lessons/',  login_required(LessonView.as_view()), name='lessons'),
    path("lesson/<int:pk>/", login_required(LessonUpdateView.as_view()),
         name="lesson-update"),
    path("lesson/<int:pk>/status/",
         login_required(lesson_status_update), name="lesson-status-update"),
    path("lesson/<int:pk>/detail/",
         login_required(LessonDetailView.as_view()), name="lesson-detail"),
    path("lesson/<int:pk>/delete/",
         login_required(LessonDeleteView.as_view()), name="lesson-delete"),
    path('categories/', login_required(CategoriesView.as_view()), name='categories'),
    path("categories/<int:pk>/",
         login_required(CategoriesUpdateView.as_view()), name="category-update"),
    path("categories/<int:pk>/delete/",
         login_required(CategoriesDeleteView.as_view()), name="category-delete"),
    path('quizzes/', login_required(QuizView.as_view()), name='quizzes'),
    path('quizzes/create', login_required(QuizCreateView.as_view()), name='quizzes-create'),
    path("quizzes/<int:pk>/",
         login_required(QuizUpdateView.as_view()), name="quiz-update"),
    path("quizzes/<int:pk>/delete/",
         login_required(QuizDeleteView.as_view()), name="quiz-delete"),
    path("assignments/", login_required(AssignmentListView.as_view()), name="assignments"),
    path("assignment/<int:pk>", login_required(AssignmentUpdateView.as_view()), name="assignment-update"),
    path("assignment/<int:pk>/delete", login_required(AssignmentDeleteView.as_view()), name="assignment-delete"),
    path("assignment/<int:pk>/detail", login_required(AssignmentDetailView.as_view()), name="assignment-detail"),
    path("assignment/<int:pk>/submissions", login_required(AssignmentSubmissionsView.as_view()), name="assignment-submissions"),
    path("assignment/submission/<int:pk>/review", login_required(AssignmentReviewView.as_view()), name="submission-review"),
    path("assignment/submit",login_required(AssignmentSubmitView.as_view()),name='assignment-submit'),
]

learn/core/urls.py
from django.contrib import admin
from django.urls import include, path
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt
from .settings import DEBUG

urlpatterns = [
    path("", include("app.accounts.urls", namespace="core")),
    path("chart/", include("app.charts.urls")),
    path("courses/", include("app.courses.urls")),
    path('admin/', admin.site.urls),
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True)), name="graphql"),
]

if DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

learn/app/courses/models.py
from django.db import models
from app.accounts.models import User
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator
from ..accounts.models import Enrollment


class Classes(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(
        upload_to='uploads/classes', blank=True, null=True)
    slug = models.SlugField(unique=True, max_length=255)
    latest_price = models.FloatField(
        default=0.0, validators=[MinValueValidator(0.0)])
    before_price = models.FloatField(
        default=0.0, validators=[MinValueValidator(0.0)])
    postition = models.IntegerField(blank=True, null=True)
    publish_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'classes'


class Category(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.TextField(max_length=255, blank=True, null=True)
    popular = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'categories'


class Subject(models.Model):
    name = models.CharField(max_length=255)
    short = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, max_length=255)
    image = models.ImageField(
        upload_to='uploads/subjects', blank=True, null=True)
    publish_at = models.DateTimeField(blank=True, null=True)
    standard = models.ForeignKey(Classes, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name + ' - ' + self.standard.name

    class Meta:
        db_table = 'subjects'


class Chapter(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(
        upload_to='uploads/chapters', blank=True, null=True)
    collectionid = models.CharField(
        db_column='collectionId', max_length=255, blank=True, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name + ' - ' + self.subject.name + ' - ' + self.subject.standard.name

    class Meta:
        db_table = 'chapters'


class Quiz(models.Model):
    class Type(models.TextChoices):
        Mock = 'mock', _('Mock')
        Practice = 'practice', _('Practice')

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=Type.choices)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    publish_at = models.DateTimeField(auto_now_add=True)
    time_required = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'quizzes'


class Question(models.Model):
    question_text = models.TextField()
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    figure = models.ImageField(
        upload_to='uploads/', blank=True, null=True, verbose_name=_("Figure"))

    def __str__(self):
        return self.question_text

    class Meta:
        db_table = 'questions'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.choice_text

    class Meta:
        db_table = 'choices'


class Assignment(models.Model):
    class Type(models.TextChoices):
        Mock = 'mock', _('Mock')
        Practice = 'practice', _('Practice')
    title = models.CharField(max_length=200)
    description = models.TextField()
    due_date = models.DateTimeField(blank=True, null=True)
    teacher = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True)
    assigment_file = models.FileField(upload_to='uploads/assignments', blank=True, null=True)
    type = models.CharField(max_length=20, choices=Type.choices)
    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name='assignment_created_by', blank=True, null=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='assignment_updated_by')
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class AssignmentSubmission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    solution_file = models.FileField(
        upload_to='uploads/assignments/submissions')
    reviewed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    marks = models.IntegerField(blank=True,
                                null=True,
                                validators=[MinValueValidator(0)]
    )
    remarks = models.TextField(blank=True,null=True)
    def __str__(self):
        return f"{self.assignment.title} - {self.student.full_name}"


class Grades(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    enrolled_class = models.ForeignKey(Classes, on_delete=models.CASCADE)
    assignment = models.ForeignKey(
        Assignment, null=True, blank=True, on_delete=models.CASCADE)
    quiz = models.ForeignKey(
        Quiz, null=True, blank=True, on_delete=models.CASCADE)
    grade = models.DecimalField(max_digits=2,
                                decimal_places=1,
                                validators=[MinValueValidator(0.0), MaxValueValidator(10.0)])
    # enrollment = models.ForeignKey(Enrollment,blank=False,null=False,on_delete=models.CASCADE)

    def __str__(self):
        if self.assignment:
            return f"{self.student.full_name} - Class {self.enrolled_class} - Assignment: {self.assignment.title} - Score: {self.grade}"
        elif self.quiz:
            return f"{self.student.full_name} - Class {self.enrolled_class} - Quiz: {self.quiz.name} - Score: {self.grade}"
        return f"{self.student.full_name} - Class {self.enrolled_class} - Score: {self.grade}"


class Lesson(models.Model):
    class UploadStatus(models.TextChoices):
        CREATED = 'created', _('Created')
        PENDING = 'pending', _('Pending')
        UPLOADING = 'uploading', _('Uploading')
        PROCESSING = 'processing', _('Processing')
        READY = 'ready', _('Ready')
        ERROR = 'error', _('Error')

    class LessonType(models.TextChoices):
        NONE = None, _('---------')
        VIDEO = 'video', _('Video')
        DOCUMENT = 'document', _('Document')
        IMAGE = 'image', _('Image')
        TEXT = 'text', _('Text')
        QUIZ = 'quiz', _('Quiz')

    class SupportPlatform(models.TextChoices):
        FILE = 'file', _('File')
        YOUTUBE = 'youtube', _('Youtube')
        VIMEO = 'vimeo', _('Vimeo')

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    length = models.FloatField(blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    thumb_url = models.ImageField(
        upload_to='uploads/lessons', blank=True, null=True)
    public = models.BooleanField(default=False)
    position = models.IntegerField(blank=True, null=True, default=9999)
    lesson_type = models.CharField(
        db_column='type', max_length=8, choices=LessonType.choices, default=None)
    status = models.CharField(
        max_length=10, choices=UploadStatus.choices, default=UploadStatus.CREATED)
    platform = models.CharField(
        max_length=11, blank=True, null=True, choices=SupportPlatform.choices, default=None)
    platform_video_id = models.CharField(max_length=255, blank=True, null=True)
    teacher = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='teacher')
    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name='created_by', blank=True, null=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='updated_by')
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    quiz = models.ForeignKey(
        Quiz, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:

learn/app/courses/views/categories.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
# from django.utils.text import slugify
from django.urls import reverse_lazy
from ..models import Category
from ..forms import CategoriesForm


class CategoriesView(ListView):
    model = Category
    template_name = "categories/index.html"
    form = CategoriesForm
    context_object_name = "categories"
    extra_context = {
        'title': 'Categories',
        'breadcrumbs': [{'url': 'core:home', 'label': 'Dashboard'}, {'label': 'Courses'}, {'label': 'Categories'}],
        'form': form
    }
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for obj in context[self.context_object_name]:
            temp_form = CategoriesForm(instance=obj)
            obj.form = temp_form
        return context

    # create
    def post(self, request, **kwargs):
        form = self.form(request.POST)
        self.extra_context.update({'form': form})
        if form.is_valid():
            instance = form.save(commit=False)
            # instance.slug = slugify(instance.name)
            instance.save()
            messages.success(
                request, f'{instance.name} has been created successfully.')
            self.extra_context.update({'form': CategoriesForm})
            return redirect('courses:categories')
        else:
            messages.error(request, f'failed to create! please see the create form for more details.')
            return super().get(request, **kwargs)

    #filter
    def get_queryset(self):
        queryset = super().get_queryset()
        subject_name = self.request.GET.get('subject')

        if subject_name:
            queryset = queryset.filter(name__icontains=subject_name)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subject_filter'] = self.request.GET.get('subject', '')
        return context


class CategoriesUpdateView(UpdateView):
    model = Category
    form_class = CategoriesForm
    success_url = reverse_lazy("courses:categories")
    template_name = "form.html"

    def form_valid(self, form):
        # form.instance.slug = slugify(form.instance.name)
        messages.info(
            self.request, f'{form.instance.name} has been updated successfully.')
        return super().form_valid(form)


class CategoriesDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy("courses:categories")

    def get(self, request, **kwargs):
        messages.error(request, 'Category has been deleted successfully.')
        return self.delete(request, **kwargs)

learn/app/courses/templates/lessons/form_snippet.html
<div class="form-control">
  <label for="{{ form.title.id_for_label }}">
    <span class="label-text">{{ form.title.label }}</span>
  </label>
  {{ form.title }}
  <label class="text-error">{{ form.title.errors }}</label>
</div>
<div class="form-control md:col-span-2">
  <label for="{{ form.description.id_for_label }}">
    <span class="label-text">{{ form.description.label }}</span>
  </label>
  {{ form.description }}
  <label class="text-error">{{ form.description.errors }}</label>
</div>
<div class="form-control">
  <label for="{{ form.thumb_url.id_for_label }}">
    <span class="label-text">{{ form.thumb_url.label }}</span>
  </label>
  {{ form.thumb_url }}
  <label class="text-error">{{ form.thumb_url.errors }}</label>
</div>
<div class="form-control">
  <label for="{{ form.lesson_type.id_for_label }}">
    <span class="label-text">{{ form.lesson_type.label }}</span>
  </label>
  {{ form.lesson_type }}
  <label class="text-error">{{ form.lesson_type.errors }}</label>
</div>
<div id="quiz_div_{{ form.prefix }}" class="form-control hidden">
  <label for="{{ form.quiz.id_for_label }}">
    <span class="label-text">{{ form.quiz.label }}</span>
  </label>
  {{ form.quiz }}
  <label class="text-error">{{ form.quiz.errors }}</label>
</div>
<div id="platform_div_{{ form.prefix }}" class="form-control hidden">
  <label for="{{ form.platform.id_for_label }}">
    <span class="label-text">{{ form.platform.label }}</span>
  </label>
  {{ form.platform }}
  <label class="text-error">{{ form.platform.errors }}</label>
</div>
<div id="url_div_{{ form.prefix }}" class="form-control hidden">
  <label for="{{ form.url.id_for_label }}">
    <span class="label-text">{{ form.url.label }}</span>
  </label>
  {{ form.url }}
  <label class="text-error">{{ form.url.errors }}</label>
</div>
<div class="form-control">
  <label for="{{ form.chapter.id_for_label }}">
    <span class="label-text">{{ form.chapter.label }}</span>
  </label>
  {{ form.chapter }}
  <label class="text-error">{{ form.chapter.errors }}</label>
</div>
<div class="form-control">
  <label for="{{ form.teacher.id_for_label }}">
    <span class="label-text">{{ form.teacher.label }}</span>
  </label>
  {{ form.teacher }}
  <label class="text-error">{{ form.teacher.errors }}</label>
</div>
<div class="form-control">
  <label for="{{ form.public.id_for_label }}">
    <span class="label-text">{{ form.public.label }}</span>
  </label>
  {{ form.public }}
  <label class="text-error">{{ form.public.errors }}</label>
</div>
<script>
  $(document).ready(function() {
    // Function to toggle visibility of platform field
    function toggleFields{{ form.prefix }}() {
      var lessonType = $("#{{ form.lesson_type.id_for_label }}").val();
      if (lessonType === "video") {
        $("#platform_div_{{ form.prefix }}").removeClass("hidden");
      }else if (lessonType === "quiz") {
        $("#quiz_div_{{ form.prefix }}").removeClass("hidden");
      } else {
        $("#quiz_div_{{ form.prefix }}").addClass("hidden");
        $("#platform_div_{{ form.prefix }}").addClass("hidden");
        $("{{ form.platform.id_for_label }}").val("");
      }
    }
    // Function to toggle visibility of url field
    function togglePlatform{{ form.prefix }}() {
      var platform = $("#{{ form.platform.id_for_label }}").val();
      if (platform === "youtube" || platform === "vimeo") {
        $("#url_div_{{ form.prefix }}").removeClass("hidden");
      } else {
        $("#url_div_{{ form.prefix }}").addClass("hidden");
      }
    }
    // Call the toggleFields function on page load
    toggleFields{{ form.prefix }}();
    togglePlatform{{ form.prefix }}();
  
    // Call the toggleFields function when lesson type changes
    $("#{{ form.lesson_type.id_for_label }}").change(function() {
      toggleFields{{ form.prefix }}();
    });
    // Call the togglePlatform function when platform changes
    $("#{{ form.platform.id_for_label }}").change(function() {
      togglePlatform{{ form.prefix }}();
    });
  });
</script>

learn/app/courses/templates/lessons/index.html
{% extends "layouts/dashboard.html" %}
{% load static %}
{% load truncate %}
{% block title %}
  {{ title }} | Pramey Shala
{% endblock title %}
{% block content %}
  <div class="mt-12 mb-8 flex flex-col gap-12">
    <div class="flex justify-between px-6">
      {% if perms.courses.add_lesson %}
        <button onclick="create_chapter.showModal()"
                class="btn bg-gradient-to-br from-purple-600 to-pink-400 text-white px-12 border-0 shadow-md shadow-purple-500/50">
          <i class="far fa-plus"></i>Add Lesson
        </button>
      {% endif %}
      <form method="get" class="bg-white shadow-sm p-2 rounded-xl">
        <input class="input input-bordered"
               type="text"
               name="search"
               placeholder="Search..."
               value="{{ request.GET.search }}">
        <button class="btn btn-square bg-gradient-to-br from-purple-600 to-indigo-400 text-white px-6 border-0 shadow-md shadow-indigo-500/50"
                type="submit">
          <i class="fa-regular fa-magnifying-glass"></i>
        </button>
        <a class="btn btn-square bg-gradient-to-br from-deep-orange-600 to-orange-800 text-white px-4 border-0 shadow-md shadow-deep-orange-500/50"
           href="{% url 'courses:lessons' %}"><i class="fa-regular fa-x"></i></a>
      </form>
    </div>
    <div class="relative flex w-full flex-col rounded-xl bg-base-100 bg-clip-border text-base-content shadow-md">
      <div class="relative mx-4 -mt-6 mb-4 grid px-6 py-8 overflow-hidden rounded-xl bg-gradient-to-tr from-indigo-600 to-indigo-400 bg-clip-border text-white shadow-lg shadow-indigo-500/40">
        <h1 class="block font-sans leading-snug tracking-normal text-white antialiased text-lg font-semibold">{{ title }}</h1>
      </div>
      <div class="flex flex-col gap-4 p-6 overflow-x-auto">
        <table class="table table-auto">
          <thead class="uppercase text-sm">
            <tr>
              <th class="px-4 py-3">Title</th>
              <th class="px-4 py-3">Description</th>
              <th class="px-4 py-3">Chapter</th>
              <th class="px-4 py-3">Lesson Type</th>
              <th class="px-4 py-3">Status</th>
              <th class="px-4 py-3">Action</th>
            </tr>
          </thead>
          <tfoot class="border-t border-blue-gray-50 py-3 px-5 text-left font-bold uppercase text-blue-gray-400 text-sm">
            <tr>
              <th class="px-4 py-3">Title</th>
              <th class="px-4 py-3">Description</th>
              <th class="px-4 py-3">Chapter</th>
              <th class="px-4 py-3">Lesson Type</th>
              <th class="px-4 py-3">Status</th>
              <th class="px-4 py-3">Action</th>
            </tr>
          </tfoot>
          <tbody>
            {% for lesson in lessons %}
              <tr class="border-b border-blue-gray-50">
                <td class="px-4 py-3">{{ lesson.title }}</td>
                <td class="px-4 py-3">{{ lesson.description|truncatewords_by_chars:60 }}</td>
                <td class="px-4 py-3">{{ lesson.chapter }}</td>
                <td class="px-4 py-3 capitalize">{{ lesson.lesson_type }}</td>
                <td class="px-4 py-3 {% if lesson.status != 'ready' and lesson.lesson_type == 'video' %}bg-warning/70 text-warning-content{% endif %} capitalize">
                  {% if lesson.status != 'ready' and lesson.lesson_type == 'video' %}<i class="fad fa-warning mr-1"></i>{% endif %}
                  {{ lesson.status }}
                </td>
                <td class="flex gap-2 px-4 py-3">
                  <a href="{% url 'courses:lesson-detail' pk=lesson.pk %}"
                     class="btn btn-info btn-sm">
                    <i class="fad fa-eye"></i>
                    Show
                  </a>
                  {% if perms.courses.change_lesson %}
                    <button onclick="update_lesson_{{ lesson.pk }}.showModal()"
                            class="btn btn-sm btn-success btn-square">
                      <i class="fad fa-edit"></i>
                    </button>
                  {% endif %}
                  {% if perms.courses.delete_lesson %}
                    <a href="{% url 'courses:lesson-delete' pk=lesson.pk %}"
                       onclick="if(confirm('Are you sure you want to delete {{ class.name }} from database?')) return true; else return false;"
                       class="btn btn-sm btn-error btn-square">
                      <i class="far fa-trash-alt"></i>
                    </a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="p-5 flex justify-end">
        <div class="join">
          {% if page_obj.has_previous %}
            <a class="join-item btn btn-primary"
               href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
          <span class="join-item btn btn-disabled">Page {{ page_obj.number }} of {{ paginator.num_pages }}.</span>
          {% if page_obj.has_next %}
            <a class="join-item btn btn-primary"
               href="?page={{ page_obj.next_page_number }}">next</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% if perms.courses.add_lesson %}
    <dialog id="create_chapter"
            class="modal modal-bottom sm:modal-middle transition-all duration-500 ease-in-out">
      <form method="post"
            enctype="multipart/form-data"
            class="modal-box sm:max-w-5xl">
        {% csrf_token %}
        <h2 class="font-mono font-semibold text-lg">Add New Lesson</h2>
        <div class="relative mb-4">
          <div class="w-full djanog-custom-forms grid grid-flow-dense grid-cols-1 md:grid-cols-2 gap-4">{{ form }}</div>
        </div>
        <div class="modal-action justify-between">
          <p class="text-xs mt-auto">Press esc to close the window or outside the dialog box.</p>
          <button type="submit" class="btn btn-success">Save</button>
        </div>
      </form>
      <form method="dialog" class="modal-backdrop backdrop-blur-md">
        <button>close</button>
      </form>
    </dialog>
  {% endif %}
  {% if perms.courses.change_lesson %}
    {% for lesson in lessons %}
      <dialog id="update_lesson_{{ lesson.pk }}"
              class="modal modal-bottom sm:modal-middle transition-all duration-500 ease-in-out">
        <form method="post"
              enctype="multipart/form-data"
              action="{% url 'courses:lesson-update' pk=lesson.pk %}"
              class="modal-box sm:max-w-5xl">
          {% csrf_token %}
          <h2 class="font-mono font-semibold text-lg">
            Update - {{ lesson.title }} of {{ lesson.chapter.name }} in {{ lesson.chapter.subject.name }}
          </h2>
          <div class="relative mb-4">
            <div class="w-full djanog-custom-forms grid grid-flow-dense grid-cols-1 md:grid-cols-2 gap-4">{{ lesson.form }}</div>
          </div>
          <div class="modal-action justify-between">
            <p class="text-xs mt-auto">Press esc to close the window or outside the dialog box.</p>
            <button type="submit" class="btn btn-success shadow">Update</button>
          </div>
        </form>
        <form method="dialog" class="modal-backdrop backdrop-blur-md">
          <button>close</button>
        </form>
      </dialog>
      <script>new EasyMDE({element: document.getElementById('{{ lesson.form.description.id_for_label }}')});</script>
    {% endfor %}
  {% endif %}
{% endblock content %}
{% block head_link %}
  <link rel="stylesheet"
        href="https://unpkg.com/easymde/dist/easymde.min.css">
  <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
{% endblock head_link %}
{% block body_js %}
  <script>new EasyMDE({element: document.getElementById('{{ form.description.id_for_label }}')});</script>
{% endblock body_js %}