learn/app/accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('', home, name='home'),
    path('account/profile', profile, name='user_profile'),
    path("account/", include("django.contrib.auth.urls")),
    path('account/register/', UserRegisterView.as_view(), name='register'),
    path('account/enrollment/',
         login_required(EnrollmentView.as_view()), name='enrollment'),
    path("account/enrollment/<int:pk>/",
         login_required(EnrollmentUpdateView.as_view()), name="enrolls-update"),
    path("account/enrollment/<int:pk>/delete/",
         login_required(EnrollmentDeleteView.as_view()), name="enrolls-delete"),
    path('account/payments/', login_required(PaymentsView.as_view()), name='payments'),
    path('account/roles', login_required(RolesView.as_view()), name='roles'),
    path("account/roles/<int:pk>/",
         login_required(RolesUpdateView.as_view()), name="role-update"),
    path("account/roles/<int:pk>/delete/",
         login_required(RolesDeleteView.as_view()), name="role-delete"),
    path("account/settings/", login_required(UserSettings.as_view()),
         name="user-settings"),
    path("settings/", login_required(SettingView.as_view()), name="settings"),
    path("account/users", login_required(UsersView.as_view()), name='users'),
    path("account/users/<int:pk>/",
         login_required(UsersUpdateView.as_view()), name="user-update"),
    path("account/users/<int:pk>/delete/",
         login_required(UsersDeleteView.as_view()), name="user-delete"),
]

learn/app/courses/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *


app_name = 'courses'

urlpatterns = [
    path('classes/', login_required(ClassesView.as_view()), name='classes'),
    path("classes/<int:pk>/", login_required(ClassesUpdateView.as_view()),
         name="class-update"),
    path("classes/<int:pk>/delete/",
         login_required(ClassesDeleteView.as_view()), name="class-delete"),
    path('subjects/',  login_required(SubjectsView.as_view()), name='subjects'),
    path("subject/<int:pk>/", login_required(SubjectUpdateView.as_view()),
         name="subject-update"),
    path("subject/<int:pk>/delete/",
         login_required(SubjectDeleteView.as_view()), name="subject-delete"),
    path('chapters/',  login_required(ChapterView.as_view()), name='chapters'),
    path("chapter/<int:pk>/", login_required(ChapterUpdateView.as_view()),
         name="chapter-update"),
    path("chapter/<int:pk>/delete/",
         login_required(ChapterDeleteView.as_view()), name="chapter-delete"),
    path('lessons/',  login_required(LessonView.as_view()), name='lessons'),
    path("lesson/<int:pk>/", login_required(LessonUpdateView.as_view()),
         name="lesson-update"),
    path("lesson/<int:pk>/status/",
         login_required(lesson_status_update), name="lesson-status-update"),
    path("lesson/<int:pk>/detail/",
         login_required(LessonDetailView.as_view()), name="lesson-detail"),
    path("lesson/<int:pk>/delete/",
         login_required(LessonDeleteView.as_view()), name="lesson-delete"),
    path('categories/', login_required(CategoriesView.as_view()), name='categories'),
    path("categories/<int:pk>/",
         login_required(CategoriesUpdateView.as_view()), name="category-update"),
    path("categories/<int:pk>/delete/",
         login_required(CategoriesDeleteView.as_view()), name="category-delete"),
    path('quizzes/', login_required(QuizView.as_view()), name='quizzes'),
    path('quizzes/create', login_required(QuizCreateView.as_view()), name='quizzes-create'),
    path("quizzes/<int:pk>/",
         login_required(QuizUpdateView.as_view()), name="quiz-update"),
    path("quizzes/<int:pk>/delete/",
         login_required(QuizDeleteView.as_view()), name="quiz-delete"),
    path("assignments/", login_required(AssignmentListView.as_view()), name="assignments"),
    path("assignment/<int:pk>", login_required(AssignmentUpdateView.as_view()), name="assignment-update"),
    path("assignment/<int:pk>/delete", login_required(AssignmentDeleteView.as_view()), name="assignment-delete"),
    path("assignment/<int:pk>/detail", login_required(AssignmentDetailView.as_view()), name="assignment-detail"),
    path("assignment/<int:pk>/submissions", login_required(AssignmentSubmissionsView.as_view()), name="assignment-submissions"),
    path("assignment/submission/<int:pk>/review", login_required(AssignmentReviewView.as_view()), name="submission-review"),
    path("assignment/submit",login_required(AssignmentSubmitView.as_view()),name='assignment-submit'),
]

learn/core/urls.py
from django.contrib import admin
from django.urls import include, path
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt
from .settings import DEBUG

urlpatterns = [
    path("", include("app.accounts.urls", namespace="core")),
    path("chart/", include("app.charts.urls")),
    path("courses/", include("app.courses.urls")),
    path('admin/', admin.site.urls),
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True)), name="graphql"),
]

if DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

learn/app/courses/models.py
from django.db import models
from app.accounts.models import User
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator
from ..accounts.models import Enrollment


class Classes(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(
        upload_to='uploads/classes', blank=True, null=True)
    slug = models.SlugField(unique=True, max_length=255)
    latest_price = models.FloatField(
        default=0.0, validators=[MinValueValidator(0.0)])
    before_price = models.FloatField(
        default=0.0, validators=[MinValueValidator(0.0)])
    postition = models.IntegerField(blank=True, null=True)
    publish_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'classes'


class Category(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.TextField(max_length=255, blank=True, null=True)
    popular = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'categories'


class Subject(models.Model):
    name = models.CharField(max_length=255)
    short = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, max_length=255)
    image = models.ImageField(
        upload_to='uploads/subjects', blank=True, null=True)
    publish_at = models.DateTimeField(blank=True, null=True)
    standard = models.ForeignKey(Classes, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name + ' - ' + self.standard.name

    class Meta:
        db_table = 'subjects'


class Chapter(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(
        upload_to='uploads/chapters', blank=True, null=True)
    collectionid = models.CharField(
        db_column='collectionId', max_length=255, blank=True, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name + ' - ' + self.subject.name + ' - ' + self.subject.standard.name

    class Meta:
        db_table = 'chapters'


class Quiz(models.Model):
    class Type(models.TextChoices):
        Mock = 'mock', _('Mock')
        Practice = 'practice', _('Practice')

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=Type.choices)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    publish_at = models.DateTimeField(auto_now_add=True)
    time_required = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'quizzes'


class Question(models.Model):
    question_text = models.TextField()
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    figure = models.ImageField(
        upload_to='uploads/', blank=True, null=True, verbose_name=_("Figure"))

    def __str__(self):
        return self.question_text

    class Meta:
        db_table = 'questions'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.choice_text

    class Meta:
        db_table = 'choices'


class Assignment(models.Model):
    class Type(models.TextChoices):
        Mock = 'mock', _('Mock')
        Practice = 'practice', _('Practice')
    title = models.CharField(max_length=200)
    description = models.TextField()
    due_date = models.DateTimeField(blank=True, null=True)
    teacher = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True)
    assigment_file = models.FileField(upload_to='uploads/assignments', blank=True, null=True)
    type = models.CharField(max_length=20, choices=Type.choices)
    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name='assignment_created_by', blank=True, null=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='assignment_updated_by')
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class AssignmentSubmission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    solution_file = models.FileField(
        upload_to='uploads/assignments/submissions')
    reviewed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    marks = models.IntegerField(blank=True,
                                null=True,
                                validators=[MinValueValidator(0)]
    )
    remarks = models.TextField(blank=True,null=True)
    def __str__(self):
        return f"{self.assignment.title} - {self.student.full_name}"


class Grades(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    enrolled_class = models.ForeignKey(Classes, on_delete=models.CASCADE)
    assignment = models.ForeignKey(
        Assignment, null=True, blank=True, on_delete=models.CASCADE)
    quiz = models.ForeignKey(
        Quiz, null=True, blank=True, on_delete=models.CASCADE)
    grade = models.DecimalField(max_digits=2,
                                decimal_places=1,
                                validators=[MinValueValidator(0.0), MaxValueValidator(10.0)])
    # enrollment = models.ForeignKey(Enrollment,blank=False,null=False,on_delete=models.CASCADE)

    def __str__(self):
        if self.assignment:
            return f"{self.student.full_name} - Class {self.enrolled_class} - Assignment: {self.assignment.title} - Score: {self.grade}"
        elif self.quiz:
            return f"{self.student.full_name} - Class {self.enrolled_class} - Quiz: {self.quiz.name} - Score: {self.grade}"
        return f"{self.student.full_name} - Class {self.enrolled_class} - Score: {self.grade}"


class Lesson(models.Model):
    class UploadStatus(models.TextChoices):
        CREATED = 'created', _('Created')
        PENDING = 'pending', _('Pending')
        UPLOADING = 'uploading', _('Uploading')
        PROCESSING = 'processing', _('Processing')
        READY = 'ready', _('Ready')
        ERROR = 'error', _('Error')

    class LessonType(models.TextChoices):
        NONE = None, _('---------')
        VIDEO = 'video', _('Video')
        DOCUMENT = 'document', _('Document')
        IMAGE = 'image', _('Image')
        TEXT = 'text', _('Text')
        QUIZ = 'quiz', _('Quiz')

    class SupportPlatform(models.TextChoices):
        FILE = 'file', _('File')
        YOUTUBE = 'youtube', _('Youtube')
        VIMEO = 'vimeo', _('Vimeo')

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    length = models.FloatField(blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    thumb_url = models.ImageField(
        upload_to='uploads/lessons', blank=True, null=True)
    public = models.BooleanField(default=False)
    position = models.IntegerField(blank=True, null=True, default=9999)
    lesson_type = models.CharField(
        db_column='type', max_length=8, choices=LessonType.choices, default=None)
    status = models.CharField(
        max_length=10, choices=UploadStatus.choices, default=UploadStatus.CREATED)
    platform = models.CharField(
        max_length=11, blank=True, null=True, choices=SupportPlatform.choices, default=None)
    platform_video_id = models.CharField(max_length=255, blank=True, null=True)
    teacher = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='teacher')
    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name='created_by', blank=True, null=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='updated_by')
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    quiz = models.ForeignKey(
        Quiz, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:

learn/templates/menu/list_item.html
<li>
  <a href="{% url 'core:home' %}"
     {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}
     data-ripple-light="true">
    <i class="far fa-home"></i>Home</a>
</li>
<li>
  <a href="{% url 'core:user_profile' %}"
     {% if request.resolver_match.url_name == 'user_profile' %}class="active"{% endif %}
     data-ripple-light="true"><i class="far fa-user"></i>Profile</a>
</li>
{% if perms.courses %}<li class="p-4 font-bold">Courses</li>{% endif %}
{% if perms.courses.view_classes %}
  <li>
    <a href="{% url 'courses:classes' %}"
       {% if request.resolver_match.url_name == 'classes' %}class="active"{% endif %}
       data-ripple-light="true"><i class="far fa-screen-users"></i>Classes</a>
  </li>
{% endif %}
{% if perms.courses.view_subject %}
  <li>
    <a href="{% url 'courses:categories' %}"
       {% if request.resolver_match.url_name == 'categories' %}class="active"{% endif %}
       data-ripple-light="true"><i class="far fa-sitemap"></i>Categories</a>
  </li>
  <li>
    <a href="{% url 'courses:subjects' %}"
       {% if request.resolver_match.url_name == 'subjects' %}class="active"{% endif %}
       data-ripple-light="true"><i class="far fa-books"></i>Subjects</a>
  </li>
{% endif %}
{% if perms.courses.view_chapter %}
  <li>
    <a href="{% url 'courses:chapters' %}"
       {% if request.resolver_match.url_name == 'chapters' %}class="active"{% endif %}
       data-ripple-light="true"><i class="fa-regular fa-book"></i>Chapters</a>
  </li>
{% endif %}
{% if perms.courses.view_lesson %}
  <li>
    <a href="{% url 'courses:lessons' %}"
       {% if request.resolver_match.url_name == 'lessons' %}class="active"{% endif %}
       data-ripple-light="true"><i class="fa-regular fa-chalkboard"></i>Lessons</a>
  </li>
{% endif %}
{% if perms.courses.view_quizzes %}
  <li>
    <a href="{% url 'courses:quizzes' %}"
       {% if request.resolver_match.url_name == 'quizzes' %}class="active"{% endif %}
       data-ripple-light="true"><i class="fa-regular fa-circle-question"></i>Quizzes</a>
  </li>
{% endif %}
{% if perms.courses.view_assignments %}
  <li>
    <a href="{% url 'courses:assignments' %}"
       {% if request.resolver_match.url_name == 'assignments' %}class="active"{% endif %}
       data-ripple-light="true"><i class="fa-regular fa-file-word"></i>Assignment</a>
  </li>
{% endif %}
{% if perms.accounts %}<li class="p-4 font-bold">Accounts</li>{% endif %}
{% if perms.accounts.view_enrollment %}
  <li>
    <a href="{% url 'accounts:enrollment' %}"
       {% if request.resolver_match.url_name == 'enrollment' %}class="active"{% endif %}
       data-ripple-light="true"><i class="fa-regular fa-user-plus"></i>Enrollment</a>
  </li>
{% endif %}
{% if perms.accounts.view_payments %}
  <li>
    <a href="{% url 'accounts:payments' %}"
       {% if request.resolver_match.url_name == 'payments' %}class="active"{% endif %}
       data-ripple-light="true"><i class="fa-regular fa-credit-card"></i>Payments</a>
  </li>
{% endif %}
<li class="p-4 font-bold">User Management</li>
{% if perms.accounts.view_role %}
  <li>
    <a href="{% url 'accounts:roles' %}"
       {% if request.resolver_match.url_name == 'roles' %}class="active"{% endif %}
       data-ripple-light="true"><i class="far fa-user-tag"></i>Roles</a>
  </li>
{% endif %}
{% if perms.accounts.view_users %}
  <li>
    <a href="{% url 'accounts:users' %}"
       {% if request.resolver_match.url_name == 'users' %}class="active"{% endif %}
       data-ripple-light="true"><i class="far fa-users"></i>Users</a>
  </li>
{% endif %}
<li>
  <a href="{% url 'accounts:user-settings' %}"
     {% if request.resolver_match.url_name == 'user-settings' %}class="active"{% endif %}
     data-ripple-light="true"><i class="fa-regular fa-user-pen"></i>User Settings</a>
</li>
{% if user.is_superuser %}
  <li>
    <a href="{% url 'accounts:settings' %}"
       {% if request.resolver_match.url_name == 'settings' %}class="active"{% endif %}
       data-ripple-light="true"><i class="fa-regular fa-gear"></i>General Settings</a>
  </li>
  <li>
    <a href="{% url 'graphql' %}"><i class="fa-regular fa-star-of-life"></i>Graphql API</a>
  </li>
{% endif %}