learn/app/accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('', home, name='home'),
    path('account/profile', profile, name='user_profile'),
    path("account/", include("django.contrib.auth.urls")),
    path('account/register/', UserRegisterView.as_view(), name='register'),
    path('account/enrollment/',
         login_required(EnrollmentView.as_view()), name='enrollment'),
    path("account/enrollment/<int:pk>/",
         login_required(EnrollmentUpdateView.as_view()), name="enrolls-update"),
    path("account/enrollment/<int:pk>/delete/",
         login_required(EnrollmentDeleteView.as_view()), name="enrolls-delete"),
    path('account/payments/', login_required(PaymentsView.as_view()), name='payments'),
    path('account/roles', login_required(RolesView.as_view()), name='roles'),
    path("account/roles/<int:pk>/",
         login_required(RolesUpdateView.as_view()), name="role-update"),
    path("account/roles/<int:pk>/delete/",
         login_required(RolesDeleteView.as_view()), name="role-delete"),
    path("account/settings/", login_required(UserSettings.as_view()),
         name="user-settings"),
    path("settings/", login_required(SettingView.as_view()), name="settings"),
    path("account/users", login_required(UsersView.as_view()), name='users'),
    path("account/users/<int:pk>/",
         login_required(UsersUpdateView.as_view()), name="user-update"),
    path("account/users/<int:pk>/delete/",
         login_required(UsersDeleteView.as_view()), name="user-delete"),
]

learn/core/urls.py
from django.contrib import admin
from django.urls import include, path
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt
from .settings import DEBUG

urlpatterns = [
    path("", include("app.accounts.urls", namespace="core")),
    path("chart/", include("app.charts.urls")),
    path("courses/", include("app.courses.urls")),
    path('admin/', admin.site.urls),
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True)), name="graphql"),
]

if DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

learn/app/accounts/views/dashboard.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model


User = get_user_model()


@login_required()
def home(request):
    title = 'Home'
    breadcrumbs = [{'url': 'core:home',
                    'label': 'Dashboard'}, {'label': 'Home'}]
    context = {'title': title, 'breadcrumbs': breadcrumbs}

    return render(request, 'accounts/home.html', context)


@login_required
def profile(request):
    context = {
        'title': "Profile",
        'breadcrumbs': [{'url': 'core:home', 'label': 'Dashboard'}, {'label': "User's Profile"}]
    }
    return render(request, 'accounts/users/profile.html', context)

learn/app/accounts/views/enrollment.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.utils.text import slugify
from django.utils.timezone import now
from django.urls import reverse_lazy
from ..models import Enrollment
from ..forms import EnrollmentForm
from dateutil.relativedelta import relativedelta
from django.db.models import Q


class EnrollmentView(PermissionRequiredMixin, ListView):
    permission_required = "accounts.view_enrollment"
    model = Enrollment
    template_name = "accounts/enrollment/index.html"
    form = EnrollmentForm
    context_object_name = "enrollment"
    extra_context = {
        'title': 'Enrollment',
        'breadcrumbs': [{'url': 'core:home', 'label': 'Dashboard'}, {'label': 'Accounts'}, {'label': 'Enrollment'}],
        'form': form
    }
    paginate_by = 10
    ordering = ['-expiration_date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('search', '')
        for obj in context['enrollment']:
            temp_form = EnrollmentForm(instance=obj)
            obj.form = temp_form
        return context

    # create
    def post(self, request, **kwargs):
        form = self.form(request.POST)
        self.extra_context.update({'form': form})
        if form.is_valid():
            instance = form.save(commit=False)
            instance.expiration_date = now() + relativedelta(years=1)
            instance.save()
            messages.success(request, 'Enrolled successfully.')
            self.extra_context.update({'form': EnrollmentForm})
            return redirect('accounts:enrollment')
        else:
            messages.error(
                request, f'failed to create! please see the create form for more details.')
            return super().get(request, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()

        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(
                Q(user__full_name__icontains=search_query) |
                Q(user__email__icontains=search_query) |
                Q(user__phone_number__icontains=search_query) |
                Q(standard__name__icontains=search_query)
            )

        return queryset


class EnrollmentUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = "accounts.change_enrollment"
    model = Enrollment
    form_class = EnrollmentForm
    success_url = reverse_lazy("accounts:enrollment")
    template_name = "form.html"

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.status)
        messages.info(
            self.request, 'Enrollment has been updated successfully.')
        return super().form_valid(form)


class EnrollmentDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "accounts.delete_enrollment"
    model = Enrollment
    success_url = reverse_lazy("accounts:enrollment")

    def get(self, request, **kwargs):
        messages.error(request, 'Enrollment has been deleted successfully.')
        return self.delete(request, **kwargs)

learn/app/accounts/views/payments.py
from typing import Any
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.utils.text import slugify
from django.urls import reverse_lazy
from ..models import Payments
from django.db.models import Q



class PaymentsView(PermissionRequiredMixin, ListView):
    permission_required = "accounts.view_payments"
    model = Payments
    template_name = "accounts/payments/index.html"
    context_object_name = "payments"
    extra_context = {
        'title': 'Payments',
        'breadcrumbs': [{'url': 'core:home', 'label': 'Dashboard'}, {'label': 'Accounts'}, {'label': 'Payments'}],

    }
    paginate_by = 10
    ordering = ['-created_at']

    def get_queryset(self):
        queryset = super().get_queryset()

        search_query = self.request.GET.get('search')
        if search_query:
           queryset = queryset.filter(
               Q(payment_gateway_id__icontains=search_query) |
               Q(user__full_name__icontains=search_query) |
               Q(status__iexact=search_query) |
               Q(method__icontains=search_query)
           )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('search', '')
        return context

learn/app/accounts/views/roles.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils.text import slugify
from django.urls import reverse_lazy
from ..models import Role
from ..forms import RolesForm


class RolesView(PermissionRequiredMixin, ListView):
    permission_required = "accounts.view_role"
    model = Role
    template_name = "accounts/roles/index.html"
    form = RolesForm
    context_object_name = "roles"
    extra_context = {
        'title': 'Roles',
        'breadcrumbs': [{'url': 'core:home', 'label': 'Dashboard'}, {'label': 'User Management'}, {'label': 'Roles'}],
        'form': form
    }
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for obj in context[self.context_object_name]:
            temp_form = RolesForm(instance=obj)
            obj.form = temp_form
        return context

    # create
    def post(self, request, **kwargs):
        form = self.form(request.POST)
        self.extra_context.update({'form': form})
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            permissions = form.cleaned_data['permissions']
            instance.permissions.set(permissions)
            messages.success(
                request, f'{instance.name} has been created successfully.')
            self.extra_context.update({'form': RolesForm})
            return redirect('accounts:roles')
        else:
            messages.error(request, f'failed to create! please see the create form for more details.')
            return super().get(request, **kwargs)


class RolesUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = "accounts.change_role"
    model = Role
    form_class = RolesForm
    success_url = reverse_lazy("accounts:roles")
    template_name = "courses/form.html"

    def form_valid(self, form):
        messages.info(
            self.request, f'{form.instance.name} has been updated successfully.')
        return super().form_valid(form)


class RolesDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "accounts.delete_role"
    model = Role
    success_url = reverse_lazy("accounts:roles")

    def get(self, request, **kwargs):
        messages.error(request, 'Role has been deleted successfully.')
        return self.delete(request, **kwargs)

learn/app/accounts/views/settings.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import View
from ..models import Settings, UserSettings


class SettingView(PermissionRequiredMixin, View):
    permission_required = "accounts.view_settings"
    template_name = 'accounts/settings.html'
    context = {
        'title': "General Settings",
        'breadcrumbs': [{'url': 'core:home', 'label': 'Dashboard'}, {'label': "General Settings"}]
    }

    def get(self, request):
        return render(request, self.template_name, context=self.context)

    def post(self, request):
        return render(request, self.template_name, context=self.context)


class UserSettings(View):
    template_name = 'accounts/settings.html'
    context = {
        'title': "Your Settings",
        'breadcrumbs': [{'url': 'core:home', 'label': 'Dashboard'}, {'label': "Your Settings"}]
    }

    def get(self, request):
        return render(request, self.template_name, context=self.context)

    def post(self, request):
        return render(request, self.template_name, context=self.context)

learn/app/accounts/views/users.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.utils.text import slugify
from django.urls import reverse_lazy
from ..models import User, Role
from ..forms import UsersForm
from django.contrib.auth.models import Group
from django.contrib.auth.hashers import make_password
from django.db.models import Q


class UsersView(PermissionRequiredMixin, ListView):
    permission_required = "accounts.view_user"
    model = User
    template_name = "accounts/users/index.html"
    form = UsersForm
    context_object_name = "users"
    extra_context = {
        'title': 'Users',
        'breadcrumbs': [{'url': 'core:home', 'label': 'Dashboard'}, {'label': 'User Management'}, {'label': 'Users'}],
        'form': form
    }
    paginate_by = 10
    ordering = ['-created_at']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('search', '')
        for obj in context[self.context_object_name]:
            temp_form = UsersForm(instance=obj)
            obj.form = temp_form
        return context

    # create
    def post(self, request, **kwargs):
        form = self.form(request.POST)
        self.extra_context.update({'form': form})
        if form.is_valid():
            instance = form.save(commit=False)
            instance.password = make_password(instance.password)
            instance.save()
            messages.success(
                request, f'{instance.full_name} has been created successfully.')
            self.extra_context.update({'form': UsersForm})
            return redirect('accounts:users')
        else:
            messages.error(request, f'failed to create! please see the create form for more details.')
            return super().get(request, **kwargs)


    #search
    def get_queryset(self):
        queryset = super().get_queryset()

        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(
                Q(full_name__icontains=search_query) |
                Q(email__icontains=search_query) |
                Q(phone_number__icontains=search_query) |
                Q(groups__name__icontains=search_query)
            )
        return queryset


class UsersUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = "accounts.change_user"
    model = User
    form_class = UsersForm
    success_url = reverse_lazy("accounts:users")
    template_name = "courses/form.html"

    def form_valid(self, form):
        messages.info(
            self.request, f'{form.instance.full_name} has been updated successfully.')
        return super().form_valid(form)


class UsersDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "accounts.delete_user"
    model = User
    success_url = reverse_lazy("accounts:users")

    def get(self, request, **kwargs):
        messages.error(request, 'User has been deleted successfully.')
        return self.delete(request, **kwargs)

learn/app/charts/views/users.py
from django.db.models import Count, F, Sum, Avg
from django.db.models.functions import ExtractYear, ExtractMonth
from app.accounts.models import User, Enrollment, Payments

from .json import JSONView
from ..util import months, colorPrimary, get_year_dict


class UserChart(JSONView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = self.kwargs.get("year")
        users = User.objects.filter(created_at__year=year)
        grouped_users = users.annotate(month=ExtractMonth("created_at")).values("month")\
            .annotate(count=Count("id")).order_by("month")

        users_dict = get_year_dict()

        for group in grouped_users:
            users_dict[months[group["month"]-1]] = group["count"]

        context.update({
            "data": {
                "labels": list(users_dict.keys()),
                "datasets": [{
                    "label": "Users",
                    "backgroundColor": colorPrimary,
                    "borderWidth": 1,
                    "borderRadius": 100,
                    "data": list(users_dict.values()),
                }]
            },
        })

        return context

learn/app/accounts/templates/accounts/users/index.html
{% extends "layouts/dashboard.html" %}
{% load static %}
{% block title %}
  {{ title }} | Pramey Shala
{% endblock title %}
{% block content %}
  <div class="mt-12 mb-8 flex flex-col gap-12">
    <div class="flex justify-between px-6">
      <button onclick="create_user.showModal()"
              class="btn bg-gradient-to-br from-purple-600 to-pink-400 text-white px-12 border-0 shadow-md shadow-purple-500/50">
        <i class="far fa-plus"></i>Add User
      </button>
      <form method="get" class="bg-white shadow-sm p-2 rounded-xl">
        <input class="input input-bordered"
               type="text"
               name="search"
               placeholder="Search users..."
               value="{{ request.GET.search }}">
        <button class="btn btn-square bg-gradient-to-br from-purple-600 to-indigo-400 text-white px-6 border-0 shadow-md shadow-indigo-500/50"
                type="submit"><i class="fa-regular fa-magnifying-glass"></i></button>
        <a class=" btn bg-gradient-to-br from-deep-orange-600 to-orange-800 text-white px-4 border-0 shadow-md shadow-deep-orange-500/50"
           href="{% url 'accounts:users' %}" ><i class="fa-regular fa-x"></i></a>
      </form>
    </div>
    <div class="relative flex w-full flex-col rounded-xl bg-base-100 bg-clip-border text-base-content shadow-md">
      <div class="relative mx-4 -mt-6 mb-4 grid px-6 py-8 overflow-hidden rounded-xl bg-gradient-to-tr from-indigo-600 to-indigo-400 bg-clip-border text-white shadow-lg shadow-indigo-500/40">
        <h1 class="block font-sans leading-snug tracking-normal text-white antialiased text-lg font-semibold">{{ title }}</h1>
      </div>
      <div class="flex flex-col gap-4 p-6 overflow-x-auto">
        <table class="table table-auto">
          <thead class="uppercase text-sm">
            <tr>
              <th class="px-4 py-3">APP ID#</th>
              <th class="px-4 py-3">Name</th>
              <th class="px-4 py-3">Email</th>
              <th class="px-4 py-3">Phone</th>
              <th class="px-4 py-3">Role</th>
              <th class="px-4 py-3">Joined on</th>
              <th class="px-4 py-3">Action</th>
            </tr>
          </thead>
          <tfoot class="border-t border-blue-gray-50 py-3 px-5 text-left font-bold uppercase text-blue-gray-400 text-sm">
            <tr>
              <th class="px-4 py-3">APP ID#</th>
              <th class="px-4 py-3">Name</th>
              <th class="px-4 py-3">Email</th>
              <th class="px-4 py-3">Phone</th>
              <th class="px-4 py-3">Role</th>
              <th class="px-4 py-3">Joined on</th>
              <th class="px-4 py-3">Action</th>
            </tr>
          </tfoot>
          <tbody>
            {% for user in users %}
              <tr class="border-b border-blue-gray-50">
                <td class="px-4 py-3">{{ user.id }}</td>
                <td class="px-4 py-3">{{ user.full_name }}</td>
                <td class="px-4 py-3">{{ user.email }}</td>
                <td class="px-4 py-3">{{ user.phone_number }}</td>
                <td class="px-4 py-3 capitalize">
                  <div class="max-w-xs">
                    {% if user.is_superuser %}<span class="badge badge-warning">Super User</span>{% endif %}
                    {{ user.groups.all|join:", " }}
                  </div>
                </td>
                <td class="px-4 py-3">{{ user.created_at }}</td>
                <td class="flex gap-2 px-4 py-3">
                  <button onclick="update_user_{{ user.pk }}.showModal()"
                          class="btn btn-sm btn-success btn-square">
                    <i class="fad fa-edit"></i>
                  </button>
                  <a href="{% url 'accounts:user-delete' pk=user.pk %}"
                     onclick="if(confirm('Are you sure you want to delete {{ user.full_name }} from database?')) return true; else return false;"
                     class="btn btn-sm btn-error btn-square"><i class="far fa-trash-alt"></i></a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="p-5 flex justify-end">
        <div class="join">
          {% if page_obj.has_previous %}
            <a class="join-item btn btn-primary"
               href="?page={{ page_obj.previous_page_number }}{% if search_query %}&search={{ search_query }}{% endif %}">previous</a>
          {% endif %}
          <span class="join-item btn btn-disabled">Page {{ page_obj.number }} of {{ paginator.num_pages }}.</span>
          {% if page_obj.has_next %}
            <a class="join-item btn btn-primary"
               href="?page={{ page_obj.next_page_number }}{% if search_query %}&search={{ search_query }}{% endif %}">next</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <dialog id="create_user"
          class="modal modal-bottom sm:modal-middle transition-all duration-500 ease-in-out">
    <form method="post"
          enctype="multipart/form-data"
          class="modal-box sm:max-w-5xl">
      {% csrf_token %}
      <h2 class="font-mono font-semibold text-lg">Add New User</h2>
      <div class="relative mb-4">
        <div class="form-control w-full djanog-custom-forms grid grid-cols-1 md:grid-cols-2 gap-4">{{ form.as_div }}</div>
      </div>
      <div class="modal-action justify-between">
        <p class="text-xs mt-auto">Press esc to close the window or outside the dialog box.</p>
        <button type="submit" class="btn btn-success">Save</button>
      </div>
    </form>
    <form method="dialog" class="modal-backdrop backdrop-blur-md">
      <button>close</button>
    </form>
  </dialog>
  {% for user in users %}
    <dialog id="update_user_{{ user.pk }}"
            class="modal modal-bottom sm:modal-middle transition-all duration-500 ease-in-out">
      <form method="post"
            enctype="multipart/form-data"
            action="{% url 'accounts:user-update' pk=user.pk %}"
            class="modal-box sm:max-w-5xl">
        {% csrf_token %}
        <h2 class="font-mono font-semibold text-lg">Update - {{ user.full_name }}</h2>
        <div class="relative mb-4">
          <div class="form-control w-full djanog-custom-forms grid grid-cols-1 md:grid-cols-2 gap-4">{{ user.form.as_div }}</div>
        </div>
        <div class="modal-action justify-between">
          <p class="text-xs mt-auto">Press esc to close the window or outside the dialog box.</p>
          <button type="submit" class="btn btn-success shadow">Update</button>
        </div>
      </form>
      <form method="dialog" class="modal-backdrop backdrop-blur-md">
        <button>close</button>
      </form>
    </dialog>
  {% endfor %}
{% endblock content %}

learn/app/accounts/templates/accounts/users/profile.html
{% extends "layouts/dashboard.html" %}
{% load static %}
{% block title %}
  {{ user.full_name }}'s Profile | Pramey Shala
{% endblock title %}
{% block content %}
  <div class="relative mt-8 h-72 w-full overflow-hidden rounded-xl bg-cover	bg-center">
    <div class="absolute inset-0 h-full w-full bg-blue-500/50"></div>
  </div>
  <div class="relative flex flex-col bg-clip-border rounded-xl bg-white text-gray-700 shadow-md mx-3 -mt-16 mb-6 lg:mx-4">
    <div class="p-4">
      <div class="mb-10 flex items-center justify-between gap-6">
        <div class="flex items-center gap-6">
          <div class="avatar">
            <div class="w-24 rounded-xl shadow-lg shadow-blue-gray-500/40">
              <img src="https://placehold.co/600x400"
                   width="78px"
                   height="78px"
                   alt="{{ user.full_name }}" />
            </div>
          </div>
          <div>
            <h5 class="block antialiased tracking-normal font-sans text-xl font-semibold leading-snug text-blue-gray-900 mb-1">
              {{ user.full_name }}
            </h5>
            <p class="block antialiased font-sans text-sm leading-normal font-normal text-blue-gray-600">
              {% if user.is_superuser %}<span class="badge badge-warning">Super User</span>{% endif %}
              {{ user.groups.all|join:", " }}
            </p>
          </div>
        </div>
      </div>
      <div class="gird-cols-1 mb-12 grid gap-12 px-4 lg:grid-cols-2">
        <div class="relative flex flex-col bg-clip-border bg-transparent text-gray-700 shadow p-8 rounded-xl">
          <div class="relative bg-clip-border overflow-hidden bg-transparent text-gray-700 shadow-none mx-0 mt-0 flex items-center justify-between gap-4">
            <h6 class="block antialiased tracking-normal font-sans text-base font-semibold leading-relaxed text-blue-gray-900">
              Profile Information
            </h6>
            <a class="btn btn-ghost btn-sm btn-square"><i class="fad fa-pencil"></i></a>
          </div>
          <div class="p-0">
            {% comment %} <p class="block antialiased font-sans text-sm leading-normal font-normal text-blue-gray-500">
            </p> {% endcomment %}
            <hr class="my-4 border-blue-gray-50">
            <ul class="flex flex-col gap-4 p-0">
              <li class="flex items-center gap-4">
                <p class="block antialiased font-sans text-sm leading-normal text-blue-gray-900 font-semibold capitalize">
                  first name:
                </p>
                <p class="block antialiased font-sans text-sm leading-normal font-normal text-blue-gray-500">{{ user.full_name }}</p>
              </li>
              <li class="flex items-center gap-4">
                <p class="block antialiased font-sans text-sm leading-normal text-blue-gray-900 font-semibold capitalize">mobile:</p>
                <p class="block antialiased font-sans text-sm leading-normal font-normal text-blue-gray-500">
                  {{ user.phone_number }}
                </p>
              </li>
              <li class="flex items-center gap-4">
                <p class="block antialiased font-sans text-sm leading-normal text-blue-gray-900 font-semibold capitalize">email:</p>
                <p class="block antialiased font-sans text-sm leading-normal font-normal text-blue-gray-500">{{ user.email }}</p>
              </li>
            </ul>
          </div>
        </div>
        <div class="shadow p-4 rounded-xl">
          <div class="relative bg-clip-border overflow-hidden bg-transparent text-gray-700 shadow-none mx-0 mt-0 flex items-center justify-between gap-4">
            <h6 class="block antialiased tracking-normal font-sans text-base font-semibold leading-relaxed text-blue-gray-900 mb-3">
              Platform Settings
            </h6>
          </div>
          <div class="text-lg">Comming Soon</div>
        </div>
      </div>
      <div class="px-4 pb-4">
        <h6 class="block antialiased tracking-normal font-sans text-base font-semibold leading-relaxed text-blue-gray-900 mb-2">
          Your Enrolled Courses
        </h6>
        <p class="block antialiased font-sans text-sm leading-normal font-normal text-blue-gray-500">
          You have enrolled in 4 courses
        </p>
        <div class="mt-6 grid grid-cols-1 gap-12 md:grid-cols-2 xl:grid-cols-4">
          <div class="card shadow p-4"></div>
          <div class="card shadow p-4"></div>
          <div class="card shadow p-4"></div>
          <div class="card shadow p-4"></div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}